### ISSUE TITLE
Still getting 'Unexpected token :' error with files not ending in .json

### ISSUE THREAD

**Issue by slhenty** [jessedc/ajv-cli#36] opened 2017-06-29 21:19 UTC
This is the same problem as issue https://github.com/jessedc/ajv-cli/issues/11.

I'm still getting the error when using, say, '.json5' extensions - in spite of issue #11 fix being merged and closed.

Please advise.

OS X 10.12.5
bash
ajv@5.2.0 (local install)
ajv-cli@2.1.0 (global install)

**Comment by epoberezkin** [comment] 2017-06-29 22:09
That is not the same issue, you most likely have a problem in the file itself. Extensions other than .json work for me.

**Comment by epoberezkin** [comment] 2017-08-09 19:25
@slhenty closing it, please reopen with example if the issue is not resolved.

**Closed by epoberezkin** 2017-08-09 19:25 UTC
Labels: question

**Comment by hashar** [comment] 2022-05-17 08:32
This is still an issue, I have used `ajv-cli@5.0.0` with NodeJS v12.22.5. Given:

An instance `example.json` having:
```
{"foo": "bar"}
```
And a schema `example.schema` with:
```
{"type": "object"}
```
I get:
```
$ ajv compile -s example.schema 
error:  Unexpected token ':'
```

Renaming the schema file to have a `.json` extension makes it work:
```
$ ajv compile -s example-schema.json 
schema example-schema.json is valid
```
